# Generated by Django 4.0.4 on 2022-05-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('fb_link', models.CharField(max_length=200)),
                ('insta_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceLink', models.CharField(max_length=100)),
                ('InstaLink', models.CharField(max_length=200)),
                ('twitterLink', models.CharField(max_length=200)),
                ('SiteContact', models.CharField(max_length=200)),
                ('WaltLink', models.CharField(max_length=200)),
                ('linkedLink', models.CharField(max_length=200)),
                ('mainPhone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lomge', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('birthday', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=100)),
                ('garage', models.CharField(max_length=100)),
                ('toillets', models.CharField(max_length=100)),
                ('addressName', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
            },
        ),
        migrations.CreateModel(
            name='Silder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('Img1', models.FileField(upload_to='')),
                ('Img2', models.FileField(upload_to='')),
                ('Img3', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Silder Image & Title',
                'verbose_name_plural': 'Silder Images & Titles',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mainColor', models.CharField(max_length=200)),
                ('fullSiteColor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Site Info',
                'verbose_name_plural': 'Site Infos',
            },
        ),
    ]
