# Generated by Django 4.0.4 on 2022-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceLink', models.CharField(max_length=200)),
                ('InstaLink', models.CharField(max_length=200)),
                ('twitterLink', models.CharField(max_length=200)),
                ('SiteContact', models.CharField(max_length=200)),
                ('WaltLink', models.CharField(max_length=200)),
                ('linkedLink', models.CharField(max_length=200)),
                ('mainPhone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lomge', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Silder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img1', models.ImageField(upload_to='')),
                ('Img2', models.ImageField(upload_to='')),
                ('Img3', models.ImageField(upload_to='')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mainColor', models.CharField(max_length=200)),
                ('fullSiteColor', models.CharField(max_length=200)),
            ],
        ),
    ]
